# These are supported funding model platforms

github: [lawson]
patreon: # Replace with a single Patreon username
open_collective: # Replace with a single Open Collective username
ko_fi: 
custom: ['https://buymeacoffee.com/jesselawson']
